default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: catspam
  password: 123

development:
  <<: *default
  database: catspam_development

test:
  <<: *default
  database: catspam_test

production:
  <<: *default
  database: catspam_production
